// Local original assets; provenance is recorded in public/assets/coins/SOURCES.md.
export const assetLogos: Readonly<Record<string, string>> = {
  AAVE: "/assets/coins/aave.png",
  ADA: "/assets/coins/ada.ico",
  AVAX: "/assets/coins/avax.svg",
  BCH: "/assets/coins/bch.svg",
  BNB: "/assets/coins/bnb.svg",
  BTC: "/assets/coins/btc.png",
  DOGE: "/assets/coins/doge.png",
  DOT: "/assets/coins/dot.svg",
  ETC: "/assets/coins/etc.svg",
  ETH: "/assets/coins/eth.ico",
  FIL: "/assets/coins/fil.ico",
  LINK: "/assets/coins/link.png",
  LTC: "/assets/coins/ltc.svg",
  NEAR: "/assets/coins/near.png",
  OP: "/assets/coins/op.png",
  SOL: "/assets/coins/sol.svg",
  SUI: "/assets/coins/sui.png",
  TRX: "/assets/coins/trx.svg",
  UNI: "/assets/coins/uni.png",
  USDC: "/assets/coins/usdc.svg",
  USDT: "/assets/coins/usdt.svg",
  XRP: "/assets/coins/xrp.svg",
}
